version: "3"

services:
  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./server:/srv/server
      - ./log:/var/log/nginx
    depends_on:
      - django

  django:
    container_name: django
    build: ./server
    image: server/django
    restart: always
    command: uwsgi --ini uwsgi.ini
    volumes:
      - ./server:/srv/server
      - ./log:/var/log/uwsgi
