# Generated by Django 4.2.4 on 2023-08-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('cloth_type', models.CharField(max_length=10)),
                ('max_temp', models.IntegerField()),
                ('min_temp', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('image', models.ImageField(null=True, upload_to='clothes')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
    ]
