# Generated by Django 4.1.7 on 2023-02-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_des', models.CharField(max_length=20)),
                ('temp', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=20)),
                ('top_clothes', models.CharField(max_length=20)),
                ('bottom_clothes', models.CharField(max_length=20)),
                ('one_piece', models.CharField(max_length=20)),
                ('hat', models.CharField(max_length=20)),
                ('outer_cloth', models.CharField(max_length=20)),
                ('muffler', models.BooleanField()),
                ('mask', models.BooleanField()),
            ],
        ),
    ]
