# Generated by Django 3.2 on 2023-03-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
                ('cloth_type', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=16)),
                ('temp', models.IntegerField()),
                ('sex', models.IntegerField()),
            ],
            options={
                'ordering': ['category'],
            },
        ),
    ]
