# Generated by Django 4.1.7 on 2023-03-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='bottom_clothes',
            new_name='cloth',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='mask',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='one_piece',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='top_clothes',
        ),
    ]
