# Generated by Django 4.1.7 on 2023-03-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0002_rename_bottom_clothes_clothes_cloth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottom_Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=20)),
                ('bottom_cloth', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Top_Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=20)),
                ('top_cloth', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Clothes',
        ),
    ]
