# Generated by Django 3.2 on 2023-04-03 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0002_alter_clothes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'ordering': ['?']},
        ),
    ]
