# Generated by Django 3.2 on 2023-04-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0003_alter_clothes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='image',
            field=models.ImageField(null=True, upload_to='clothes'),
        ),
    ]
