# Generated by Django 4.1.7 on 2023-03-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0003_bottom_clothes_top_clothes_delete_clothes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bottom_Clothes',
            new_name='BottomClothes',
        ),
        migrations.RenameModel(
            old_name='Top_Clothes',
            new_name='TopClothes',
        ),
    ]
