# Generated by Django 3.2 on 2023-04-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0004_clothes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.ImageField(upload_to='clothes'),
        ),
    ]
