# Generated by Django 4.1.7 on 2023-03-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0004_rename_bottom_clothes_bottomclothes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottomclothes',
            old_name='bottom_cloth',
            new_name='cloth',
        ),
        migrations.RenameField(
            model_name='bottomclothes',
            old_name='sex',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='topclothes',
            old_name='sex',
            new_name='cloth',
        ),
        migrations.RenameField(
            model_name='topclothes',
            old_name='top_cloth',
            new_name='color',
        ),
    ]
