# Generated by Django 4.1.7 on 2023-03-08 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0005_rename_bottom_cloth_bottomclothes_cloth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='BottomClothes',
        ),
        migrations.DeleteModel(
            name='TopClothes',
        ),
        migrations.AddField(
            model_name='clothes',
            name='cloth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='weatherdata.position'),
        ),
    ]
