# Generated by Django 4.1.7 on 2023-03-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0006_clothes_position_delete_bottomclothes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='cloth',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
