# Generated by Django 4.1.7 on 2023-03-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0007_alter_clothes_cloth_delete_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='position',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
