# Generated by Django 4.1.7 on 2023-03-14 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0008_clothes_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
