# Generated by Django 4.2.4 on 2023-08-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openweather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='weather',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
